name: Deploy mdBook site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4

      # Cache for mdBook
      - name: Cache mdBook
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/mdbook
          key: ${{ runner.os }}-mdbook-${{ env.MDBOOK_VERSION }}
          restore-keys: |
            ${{ runner.os }}-mdbook-

      # Install mdBook
      - name: Install mdBook
        run: |
          if ! mdbook --version | grep -q "${MDBOOK_VERSION}"; then
            curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
            rustup update
            cargo install --version ${MDBOOK_VERSION} mdbook --force
          fi

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with mdBook
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
