name: Deploy mdBook site to Pages

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
      MDBOOK_CACHE_KEY: mdbook-cache-${{ env.MDBOOK_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache mdBook
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/mdbook
          key: ${{ env.MDBOOK_CACHE_KEY }}
          restore-keys: |
            ${{ env.MDBOOK_CACHE_KEY }}
      - name: Install mdBook
        run: |
          if [ ! -x "$(command -v mdbook)" ]; then
            echo "mdBook not found in cache, installing..."
            curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            rustup update
            cargo install --version ${MDBOOK_VERSION} mdbook
          else
            echo "Using cached mdBook version"
          fi
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with mdBook
        run: mdbook build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
